# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20170503_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, upload_to='people_photos'),
        ),
    ]
